### ISSUE TITLE
Camera not working in Android 10

### ISSUE THREAD

**Issue by peterbrandtbornholdtlee** [kroegerama/bottomsheet-imagepicker#11]
Hi, the camera still is not working in Android 10, I think it is due to the scoped storage change in Android 10.
I debugged everything and the line which i giving the exception is:

BottomSheetImagePicker.kt Line 255: 
`val image = File.createTempFile(imageFileName, ".jpg", storageDir)`

This is resulting in "Method threw 'java.io.IOException' exception."

Device is One Plus 6T

**Comment by peterbrandtbornholdtlee** [comment]
Also, i tried to work around with setting "<application android:requestLegacyExternalStorage="true" ... >" in my manifest, which is resulting in:

"java.lang.SecurityException: Permission Denial"
"revoked permission android.permission.CAMERA"

**Comment by kroegerama** [comment]
Version 1.1.1 should work now :)
